### ISSUE TITLE
Instant run incompatible with cwac-anddown

### ISSUE THREAD

**Issue by Franzaine** [commonsguy/cwac-anddown#16]
When running the development version of the Fidesmo app and trying to access the cwac-anddown library I get a IllegalStateException. This only happens when running the app with Instant Run. Turning off Instant Run and running the app once again makes everything work properly. Without heavily looking into this I think the issue is similar to the following two issues with the library Realm: https://code.google.com/p/android/issues/detail?id=200052 & https://code.google.com/p/android/issues/detail?id=200635
The project Realm also has an issue for this: https://github.com/realm/realm-java/issues/1421#issuecomment-183486902

I don't expect this issue to be solved by cwac-anddown but rather as the Google developers say "will be fixed in beta7 [of Android Studio 2.0]". I think this issue was annoying enough to track down that it has some value of being open here until it is resolved by Google. In the meantime the suggestion is to turn off Instant Run in the Android Studio settings under "Build, Execution, Deployment" / "Instant Run". If you don't see the value of this issue being here until their release feel free to close it.

My stacktrace:

```
03-03 12:01:42.711 18364-18364/com.fidesmo.sec.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.fidesmo.sec.android, PID: 18364
                                                                         java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                             at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                          Caused by: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_9_f54138b24e596d9c38350def0520b82aa36feb19-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_8_b42c140b2a5995d44b8262bd423ece168f6c3134-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_7_572e625d9a85faa36fed4eccf76e9752adc4d347-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_6_988230e88edba42d7137499bcd365a70c170be3e-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_5_7caf7c41eccdb46706b4c00fa31f68abf77444e9-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_4_a6154ab258ab97d11fc704c7c4d3c64311cdd8f5-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_3_2216dfe8669a4d17c40bb753c715d062c502e099-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_2_49e629e75468a4bc7ce243a5071a1cbafa525436-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_1_ddf39f4d040f93e5ba5a733bf8b83c76ef140949-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-slice_0_7dd766466e57ec26e459338b8492dfc4984d1d97-classes.dex", dex file "/data/data/com.fidesmo.sec.android/files/instant-run/dex/slice-dependencies_0d527e6889c9ce4c5d28e076c32136d293e7759f-classes.dex"],nativeLibraryDirectories=[/data/data/com.fidesmo.sec.android/lib, /vendor/lib64, /system/lib64]]] couldn't find "libanddown.so"
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                             at java.lang.System.loadLibrary(System.java:1076)
                                                                             at com.commonsware.cwac.anddown.AndDown.<clinit>(AndDown.java:5)
                                                                             at com.fidesmo.sec.android.app_store.AppActivity.setApplicationDescription(AppActivity.java:311)
                                                                             at com.fidesmo.sec.android.app_store.AppActivity$2.call(AppActivity.java:271)
                                                                             at com.fidesmo.sec.android.app_store.AppActivity$2.call(AppActivity.java:263)
                                                                             at rx.Observable$28.onNext(Observable.java:7976)
                                                                             at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                             at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:202)
                                                                             at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                             at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                             at android.os.Handler.handleCallback(Handler.java:739) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:148) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

Android device: Huawei Nexus 6P running Android 6.0.1. Running stock, not rooted or unlocked.
Development environment: Surface Pro 3 running Linux Mint 17.3 and Android Studio 2.0 Beta 6

**Comment by commonsguy** [comment]
Closing as not really something that I can do anything about.
